version: '3.8'

services:
  shell-app:
    build:
      context: .
      dockerfile: ./workspaces/shell-app/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./workspaces/shell-app:/app
      - ./workspaces/shared:/app/shared
      - /app/node_modules
    depends_on:
      - page-vite
      - page-webpack

  page-vite:
    build:
      context: .
      dockerfile: ./workspaces/page-vite/Dockerfile
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=development
    volumes:
      - ./workspaces/page-vite:/app
      - ./workspaces/shared:/app/shared
      - /app/node_modules

  page-webpack:
    build:
      context: .
      dockerfile: ./workspaces/page-webpack/Dockerfile
    ports:
      - "3004:3004"
    environment:
      - NODE_ENV=development
    volumes:
      - ./workspaces/page-webpack:/app
      - ./workspaces/shared:/app/shared
      - /app/node_modules

  shared-ui:
    build:
      context: .
      dockerfile: ./workspaces/shared-ui/Dockerfile
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=development
    volumes:
      - ./workspaces/shared-ui:/app
      - ./workspaces/shared:/app/shared
      - /app/node_modules
