export const EVENT_TYPES = {
  NAVIGATION_REQUESTED: 'NAVIGATION_REQUESTED',
  NAVIGATION_COMPLETED: 'NAVIGATION_COMPLETED',

  MICRO_FRONTEND_MOUNTED: 'MICRO_FRONTEND_MOUNTED',
  MICRO_FRONTEND_UNMOUNTED: 'MICRO_FRONTEND_UNMOUNTED',

  STATE_CHANGED: 'STATE_CHANGED',
  STATE_REQUESTED: 'STATE_REQUESTED',

  ERROR_OCCURRED: 'ERROR_OCCURRED',

  USER_AUTHENTICATED: 'USER_AUTHENTICATED',
  USER_LOGOUT: 'USER_LOGOUT',

  DATA_FETCHED: 'DATA_FETCHED',
  DATA_UPDATED: 'DATA_UPDATED'
};

export default EVENT_TYPES;